### ISSUE TITLE
Any chance of a tagged release version?

### ISSUE THREAD

**Issue by ejunker** [TheMonkeys/laravel-cachebuster#10]
Right now the only version available is dev-master. Do you have plans to tag a specific version?

**Comment by tremby** [comment]
You can lock down a particular commit in the composer.json file: `"themonkeys/cachebuster": "dev-master#6b549c23d1076a3d1a834f48c79367ce93407a44"`

But I also vote for a proper release.

If nothing else, it makes determining if the latest version on Github is newer than the commit I've got in my composer.json file or not.

**Comment by k7n4n5t3w4rt** [comment]
+1 for a tagged release. How about when we do the Laravel 5 update?

**Comment by tremby** [comment]
It'd still be good to have on the L4 version too. I still maintain several L4 sites.

**Comment by k7n4n5t3w4rt** [comment]
Yep, noted.

The plan is to tag the current Laravel 4 one as v1.0 and then update to Laravel 5 - and tag it v2.0 I guess. So we'll be able to specify v1.0 for any future projects that use Laravel 4 if required.

Sound ok to everyone?

**Comment by tremby** [comment]
Sounds fine to me.

**Comment by taledo** [comment]
Tagged releases are now in place for both L4 and L5. The Docs / ReadMe have also been updated, which cover the differences in implementation https://github.com/TheMonkeys/laravel-cachebuster
