### ISSUE TITLE
Laravel 5.3 Support?

### ISSUE THREAD

**Issue by ejunker** [TheMonkeys/laravel-cachebuster#15]
I tried to install with Laravel 5.3 and I get an error that Laravel 5.3 requires symfony/http-kernel 3.1.\* but themonkeys/cachebuster 2.0.1 requires symfony/http-kernel 2.*

**Comment by robertzimmerman** [comment]
i second that, would love to get this working on 5.3 laravel if possible

**Comment by robertzimmerman** [comment]
hi @ejunker , i just forked the repo and made the update to the composer.json to 3.1.x and it seems to be working fine for me. so i will be using this until it is updated.

**Comment by ejunker** [comment]
I just submitted this pull request #16

**Comment by ejunker** [comment]
@lachlantweedie thanks for merging my pull request. If you tag a new version like `2.0.2` and push that tag then it will create a new version on https://packagist.org/packages/themonkeys/cachebuster so that people can start using this package with Laravel 5.3.

**Comment by lachlantweedie** [comment]
@ejunker done!
